### ISSUE TITLE
[Feat]: Insufficient information returned in case of parameter error

### ISSUE THREAD

**Issue by shiw-yang** [x-lambda/protoc-gen-gin#8]
https://github.com/x-lambda/protoc-gen-gin/blob/0b7acb6dd104d3453d75198cc9fd303a3905ee5a/generator/template.go.tpl#L69

在参数绑定时发生异常的情况，返回param error，但是具体的错误信息无返回。
导致接口在发生参数错误的时候，只能收到如下的错误返回信息，无法针对错误信息进行定位和改正。
```json
{
    "code": 400,
    "data": null,
    "msg": "params error"
}
```

可以把err.Error()的信息在data内返回，得到结构如下：

```json
{
    "code": 400,
    "data": "json: cannot unmarshal number into Go struct field XXX.AAA of type string",
    "msg": "params error"
}
```

**Comment by x-lambda** [comment]
Nice，data里面是放结构化数据的，可以把`"params error"`改成`err.Error()`

**Comment by x-lambda** [comment]
来个pr吧🚀🚀🚀

**Comment by shiw-yang** [comment]
https://github.com/x-lambda/protoc-gen-gin/pull/11

**Comment by shiw-yang** [comment]
> 来个pr吧🚀🚀🚀

https://github.com/x-lambda/protoc-gen-gin/pull/11

**Comment by shiw-yang** [comment]
#11
